language: php

php:
  - '5.5.9'
  - '7.0'
  - '7.1'

services:
  - mysql

before_script:
    - travis_retry composer self-update
    - travis_retry composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
    - travis_retry composer install --no-interaction --prefer-source --dev


script:
    - vendor/bin/phpunit
